### ISSUE TITLE
Gradle 8.2 will remove android.enableDexingArtifactTransform=false

### ISSUE THREAD

**Issue by tiagoalmeida92** [Conviva/conviva-android-coresdk#9]
Android Gradle plugin 8.2 removed an option which conviva requires, are there any plans, so our app can update gradle version? 

```
The option setting 'android.enableDexingArtifactTransform=false' is deprecated.
The current default is 'true'.
It will be removed in version 8.2 of the Android Gradle plugin.
```

**Comment by SarathRamachandra** [comment]
@tiagoalmeida92 sorry for the delay from our side, please give us some time in providing you an update you.

**Comment by rajeshkumar-sw** [comment]
Hi @tiagoalmeida92 , Please use the below property to solve this issue.

`android.useFullClasspathForDexingTransform = true`
